# Generated by Django 5.0 on 2024-05-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
