# Generated by Django 5.0 on 2024-05-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapp', '0002_store_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
