# Generated by Django 5.0 on 2024-05-26 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapp', '0004_remove_sales_name_remove_sales_quantity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
