# Generated by Django 5.0 on 2024-05-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapp', '0006_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
