# Generated by Django 5.0 on 2024-05-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapp', '0010_alter_customers_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        # migrations.AlterField(
        #     model_name='cartitem',
        #     name='quantity',
        #     field=models.IntegerField(default=1),
        # ),
    ]
