# Generated by Django 5.0 on 2024-06-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapp', '0012_alter_cartitem_quantity_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='on_credit',
            field=models.BooleanField(default=False),
        ),
    ]
