# Generated by Django 5.0 on 2024-06-02 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapp', '0013_sales_on_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Wallet', to='pharmapp.customers'),
        ),
    ]
